### ISSUE TITLE
scala213 parse error: unexpected opening parenthesis

### ISSUE THREAD

**Issue by jackpf** [scalameta/scalameta#4601]
Hi,

We recently upgraded from scalafmt `3.1.2` to `3.9.9`, however we're now getting parse errors for perfectly valid code (that didn't cause issues with version `3.1.2`).
It's also an issue in the latest `3.11.0`.

It seems to be complaining about multi-parameter lists. Here's a minimal example to reproduce with `scalafmt --check FmtTest.scala`:

```scala
trait Parent {
  protected implicit val viewConfig: String
}
class FmtTest(
  config: Int
)(override protected implicit val viewConfig: String)(
  implicit z: Double
) extends Parent
```

Gives the error:
```
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: FmtTest.scala:8: error: [dialect scala213] unexpected opening parenthesis
)(override protected implicit val viewConfig: String)(
```

But this code compiles fine with Scala `2.13.17`.

Our scalafmt config is:

```
version = "3.9.9"
maxColumn = 120
align.preset = none
runner.dialect = scala213
docstrings.wrap = "no"
```
