### ISSUE TITLE
`failed to generate semanticdb` with Scala 2.13.13 under Xsource:3

### ISSUE THREAD

**Issue by hmemcpy** [scalameta/scalameta#3597]
semanticdb-scalac version 4.9.0
scala version 2.13.13
scalacOptions: `-Xsource:3`

I encountered this just now when trying to upgrade my project to Scala 2.13.13 (we use `-Xsource:3` for some syntactic improvements). I also bumped the semanticdb version to 4.9.0.

For the following code:

```scala
trait MyTrait {
  def foo = 
     ???
}
```

I now get a compilation error:
```
[error] failed to generate semanticdb for ~/git/sbt-playground/src/main/scala/app/MyTrait.scala:
[error] ~/git/sbt-playground/src/main/scala/app/MyTrait.scala:5: error: illegal start of simple expression
[error]   def foo =
[error]            ^
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr0(ScalametaParser.scala:2292)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2245)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2228)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2107)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1704)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:319)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:366)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1609)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1508)
....
```

Moving the `???` to the same line solves this, but in some cases, the line is too big and scalafmt moves the `???` to the next line again.

In Scala 2.13.13, some previous changes for `-Xsource:3`, in particular - placing infix operators on new lines - were moved under a different flag, so the code:

```scala
   foo
     ++ bar
```

no longer compiles in 2.13.13. Maybe this is related?

**Comment by SethTisue** [comment]
Curious, does semanticdb contain `-Xsource:3` specific logic?

**Comment by hmemcpy** [comment]
Ah but I see that this issue was indeed already fixed last week! https://github.com/scalameta/scalameta/pull/3575
I'll wait for the release, then :)

**Comment by hmemcpy** [comment]
Closing this since this issue is a duplicate, and was already fixed by @kitbellew!
Looking forward to the release. Thanks!
