### ISSUE TITLE
Crash on type lambda as type parameter

### ISSUE THREAD

**Issue by belamenso** [scalameta/scalameta#4015]
## Configuration (required) ##
`.scalafmt.conf`
```
runner.dialect = scala3
version = 0.0.0
```

```
$ ./scalafmt-linux-glibc --version
scalafmt 0.0.0+1-c1c9bbb3-SNAPSHOT
```

## Command-line parameters (required) ##

```
$ ./scalafmt-linux-glibc --config .scalafmt.conf
```
## Steps

Given code like this:
```scala
trait A[B[_]]
type T1 = A[[T] =>> T match
    case _ => Int]

@main def main(): Unit = println("hello")

```

## Problem

Scalafmt crashes with the return code 2
```
$ ./scalafmt-linux-glibc --config .scalafmt.conf 
main.scala:3: error: [dialect scala3] `outdent` expected but `]` found
    case _ => Int]
                 ^
$ echo $?
2
```

## Expectation

I would like the tool to not cash and I have no style preference.

## Workaround

I've found that by placing the closing `]` on its own line the problem goes away, so this file will not crash the formatter:
```scala
trait A[B[_]]
type T1 = A[[T] =>> T match
    case _ => Int
]

@main def main(): Unit = println("hello")
```

## Notes

This is also not working on the 3.8.3, the above reproduction is on the latest binary.
```
$ scalafmt --version
scalafmt 3.8.3
```
