### ISSUE TITLE
[Scala 3] Scalameta fails to parse valid ‘if … then’ statement that has a newline immediately following the if

### ISSUE THREAD

**Issue by djneades** [scalameta/scalameta#2379]
These two (admittedly rather strangely formatted) code examples compile with Scala 3.0.0:

```scala
val x = Some(10)

def f =
   if
         x.exists(x => x == 10) then
      println("Yes")
   else
      println("No")
```

```scala
val x = Some(10)

def f =
   if
      x.exists
         (x => x == 10) then
      println("Yes")
   else
      println("No")
```

However, for both of them, Scalameta chokes on the `then`. Running Scalafmt 3.0.0-RC5 on the first example above gives:

```
sbt:test> scalafmt
[info] Formatting 1 Scala sources...
[error] C:\Git\BugReport\src\main\scala\Main.scala:5: error: ; expected but then found
[error]          x.exists(x => x == 10) then
[error]                                 ^: C:\Git\BugReport\src\main\scala\Main.scala
[error] (Compile / scalafmt) C:\Git\BugReport\src\main\scala\Main.scala:5: error: ; expected but then found
[error]          x.exists(x => x == 10) then
[error]                                 ^: C:\Git\BugReport\src\main\scala\Main.scala
[error] Total time: 0 s, completed 09-Jun-2021 00:42:34
```

Interestingly, Scalameta is fine with this valid Scala 3 code:

```scala
val x = Some(10)

def f =
   if
      x.exists
         (x => x == 10)
   then
      println("Yes")
   else
      println("No")
```

I noticed this issue while trying to characterize [this Scala 3 issue](https://github.com/lampepfl/dotty/issues/12757).

**Comment by tgodzik** [comment]
Thanks for reporting! This is due to the fact that we treat the statement after `if` as an indented block, which cannot contain a standalone `then`. Not sure how to fix that currently, since I thought that is the expected behaviour :thinking:

**Comment by djneades** [comment]
@tgodzik Ah :-)

This issue is not a problem for me, since I don’t actually have any code that looks like this. Perhaps the Scala 3 folks will take a look at my [issue](https://github.com/lampepfl/dotty/issues/12757) and tweak the compiler to be more in line with your expectations …

**Comment by kitbellew** [comment]
> Thanks for reporting! This is due to the fact that we treat the statement after `if` as an indented block, which cannot contain a standalone `then`. Not sure how to fix that currently, since I thought that is the expected behaviour 🤔

i thought indent is happening after `then`, and between `if` and `then` anything is ok...

**Comment by tgodzik** [comment]
According to https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces
indent can happen after `if`

**Comment by kitbellew** [comment]
hmm... does that mean we can do this:
```
if
  val a = b + c
  val d = foo match {
    case ...
  }
  a < d then
```

**Comment by tgodzik** [comment]
> hmm... does that mean we can do this:
> 
> ```
> if
>   val a = b + c
>   val d = foo match {
>     case ...
>   }
>   a < d then
> ```

I don't think so, you need to have the `then` keyword in a newline to end indentation. I think in case of Dotty it's ok if it's a single statement.

**Comment by kitbellew** [comment]
i am not sure scalafmt actually expects significant indentation straight after `if`. probably just `)`, `then` and `else`. @tgodzik do we need to fix that? would need examples of what's allowed...

**Comment by tgodzik** [comment]
I think that `if<indent><outdent>` is basically the same as having `if({})`. I check if it should be fixed in Scalfmt.

**Comment by tgodzik** [comment]
@kitbellew Created a PR for `if` https://github.com/scalameta/scalafmt/pull/2594

It seemed to work mostly before, but just in case I think it's better to handle it similar to else and then.

I will look into while tomorrow, but should probably be the same.
